export const AVAILABLE_EDITOR_THEMES = [
  { label: "System", value: "system" },
  { label: "Abcdef", value: "abcdef" },
  { label: "Abyss", value: "abyss" },
  { label: "Android Studio", value: "androidstudio" },
  { label: "Andromeda", value: "andromeda" },
  { label: "Atomone", value: "atomone" },
  { label: "Aura", value: "aura" },
  { label: "Bbedit", value: "bbedit" },
  { label: "Basic Light", value: "basicLight" },
  { label: "Basic Dark", value: "basicDark" },
  { label: "Bespin", value: "bespin" },
  { label: "Copilot", value: "copilot" },
  { label: "Console Light", value: "consoleLight" },
  { label: "Console Dark", value: "consoleDark" },
  { label: "Dracula", value: "dracula" },
  { label: "Darcula", value: "darcula" },
  { label: "Duotone Light", value: "duotoneLight" },
  { label: "Duotone Dark", value: "duotoneDark" },
  { label: "Eclipse", value: "eclipse" },
  { label: "Github Light", value: "githubLight" },
  { label: "Github Dark", value: "githubDark" },
  { label: "Gruvbox Dark", value: "gruvboxDark" },
  { label: "Gruvbox Light", value: "gruvboxLight" },
  { label: "Material Light", value: "materialLight" },
  { label: "Material Dark", value: "materialDark" },
  { label: "Monokai", value: "monokai" },
  { label: "Monokai Dimmed", value: "monokaiDimmed" },
  { label: "Kimbie Dark", value: "kimbieDark" },
  { label: "Noctis Lilac", value: "noctisLilac" },
  { label: "Nord", value: "nord" },
  { label: "Okaidia", value: "okaidia" },
  { label: "Quietlight", value: "quietlight" },
  { label: "Red", value: "red" },
  { label: "Solarized Light", value: "solarizedLight" },
  { label: "Solarized Dark", value: "solarizedDark" },
  { label: "Sublime", value: "sublime" },
  { label: "Tokyo Night", value: "tokyoNight" },
  { label: "Tokyo Night Storm", value: "tokyoNightStorm" },
  { label: "Tokyo Night Day", value: "tokyoNightDay" },
  { label: "Tomorrow Night Blue", value: "tomorrowNightBlue" },
  { label: "White Light", value: "whiteLight" },
  { label: "White Dark", value: "whiteDark" },
  { label: "VS Code Dark", value: "vscodeDark" },
  { label: "VS Code Light", value: "vscodeLight" },
  { label: "Xcode Light", value: "xcodeLight" },
  { label: "Xcode Dark", value: "xcodeDark" },
]
